FROM centos:7

RUN yum -y install epel-release centos-release-openshift-origin \
 && yum -y install python-virtualenv git sudo origin-clients \
 && yum clean all

RUN virtualenv /opt/apb
RUN git clone https://github.com/eriknelson/ansible-playbook-bundle && \
  cd ansible-playbook-bundle && git checkout debug
RUN source /opt/apb/bin/activate \
 && pip install -U pip setuptools
RUN source /opt/apb/bin/activate \
 && cd ansible-playbook-bundle \
 && pip install websocket-client==0.40.0 \
 && pip install -r src/requirements.txt \
 && python setup.py install
RUN echo -ne "#!/bin/bash\nsource /opt/apb/bin/activate\napb \$@" > /usr/local/bin/apb-wrapper
RUN chmod +x /usr/local/bin/apb-wrapper

RUN echo "ALL ALL=NOPASSWD: ALL" > /etc/sudoers.d/usermod
RUN chmod 666 /etc/passwd
COPY apb-wrapper /usr/local/bin/apb-wrapper
RUN chmod +x /usr/local/bin/apb-wrapper

WORKDIR /mnt

ENTRYPOINT ["bash"]
